data-moguls
2006-cpu/data-moguls pull request #18
Opened 2020-11-19 02:38 UTC by lionllopez

2020-11-21 18:07 UTC, dennisccastro approved these changes, later dismissed

2020-11-21 20:41 UTC, roboMoose requested changes
1. Fix routes for individual product end-points.
2. Remove ANY code that is not tested and/or working.
3. Think about larger app design --> use of `singleProduct` component?

2020-11-21 20:41 UTC, roboMoose commented on db/index.js
> +async function createProduct({ name, description, price, imageURL, inStock, category }) {
Make sure all functions are well tested before being committed!

2020-11-21 20:41 UTC, roboMoose commented on db/init_db.js
> +    try {
Nested try-catches? These should be separate processes.

2020-11-21 20:41 UTC, roboMoose commented on routes/index.js
>  apiRouter.get("/", (req, res, next) => {
remove any unnecessary code. This includes console logs and commented out code.

2020-11-21 20:41 UTC, roboMoose commented on routes/products.js
> +productsRouter.get("/:productId/products", async (req, res, next) => {
API route is NOT the same as the front-end react router route.

2020-11-21 20:41 UTC, roboMoose commented on routes/products.js
> +productsRouter.get("/:productId/products", async (req, res, next) => {
--> `api/products/:productId/products` ??? 
Please fix.

2020-11-21 20:41 UTC, roboMoose commented on src/api/index.js
> +    const { data } = await axios.get(`/api/products/${id}`);
Does not match API URL

2020-11-21 20:41 UTC, roboMoose commented on src/components/Allproducts.js
> +  useEffect(() => {
Make sure to include a dep:` userEffect(() => fetchAllProducts, [ ])`

2020-11-21 20:41 UTC, roboMoose commented on src/components/Allproducts.js
> +      {products.map(({ id, name, description, price, isPublic, category }) => (
Practice good React composition

2020-11-21 20:41 UTC, roboMoose commented on src/components/App.js
>    getSomething
Remove dead code. Make sure that you are using descriptive names for functions and whatnot.

2020-11-21 20:41 UTC, roboMoose commented on src/components/App.js
> +        <Navbar />
Move outside of the router.

2020-11-21 20:41 UTC, roboMoose commented on src/components/Navbar.js
> +      <NavLink to='/'><button>HOME</button></NavLink>
Don't use nested buttons. Just style the link to look like a button.

2020-11-21 20:41 UTC, roboMoose commented on src/components/Product.js
> +    useEffect(() => {
make sure to include useEffect dep.

2020-11-24 04:33 UTC, wallacepreston approved these changes
Only approving, assuming you will be good developers and fix the issues we've mentioned.  ESPECIALLY the `isAdmin` portion and the `res.sendFile` allowing all urls to send back the app.

2020-11-24 04:33 UTC, wallacepreston commented on db/init_db.js
> +          "imageURL" VARCHAR(255) DEFAULT 'imageUrl',
Insert an actual default?

2020-11-24 04:33 UTC, wallacepreston commented on db/products.js
> +            INSERT INTO products(name, description, price, "imageURL", "inStock", category)
Have we tested what happens when we call this without all of these fields?  What if `imageURL = ''`...?

2020-11-24 04:33 UTC, wallacepreston commented on db/init_db.js
> +          "imageURL" VARCHAR(255) DEFAULT 'imageUrl',
Might want to add `NOT NULL` constraint.  That way if `null` is insterted, then the default is used.

2020-11-24 04:33 UTC, wallacepreston commented on db/users.js
> +        INSERT INTO users(username, password, "firstName", "lastName", email, "imageURL", "isAdmin")
What happens if someone inserts undefined in any of these...?  Just check and see what happens... might want to error handle?

2020-11-24 04:33 UTC, wallacepreston commented on db/users.js
> +        }
Throw error if not match?

2020-11-24 04:33 UTC, wallacepreston commented on index.js
> +server.use((err, req, res, next) => {
Good job error handling!
Maybe do something a bit more fancy?
```js
console.error(error)
res.send({error: error.message, message: */ etc /*});
```

2020-11-24 04:33 UTC, wallacepreston commented on routes/products.js
> +      next({ message: "failed to pull product." });
Good explicit error handling

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +const { JWT_SECRET } = process.env;
Maybe add a default to the `JWT_SECRET`?

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +    if (password.length < 8) {
Good handling short passwords!

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +      process.env.JWT_SECRET,
Maybe just use `JWT_SECRET` instead of the whole process env var?

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +      message: "Please supply both a username and password",
Good error handling making sure both are supplied!  Use this as an example for `createProduct()`

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +  if (!auth) {
I'd rather see this in some sort of auth middleware?  Something like `requireUser` that we hav used in the past.

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +    next({
Try not to repeat code, especially so close together...

2020-11-24 04:33 UTC, wallacepreston commented on src/components/App.js
> +
Create a `<NotFound />` component? Or the redirect... however you would like the user experience to be...

2020-11-24 04:33 UTC, wallacepreston commented on src/components/Footer.js
> +import './Components.css';
I like that you're using css this way, but try to use css that only applies to this file?  Otherwise, use it in the index...

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +      isAdmin: isAdmin,
We are allowing anyone with access to postman to create an admin user.  Try doing something like 
`if(req.user.isAdmin) toInsert.isAdmin = req.body.isAdmin;`

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +
Try
```js
const toInsert = {
    username,
    password,
    firstName,
    lastName,
    email,
    imageURL,
  };

2020-11-24 04:33 UTC, wallacepreston commented on routes/users.js
> +      isAdmin: isAdmin,
DEFINITELY take care of this one!

2020-11-24 04:33 UTC, wallacepreston commented
Product Release v0.2 Beta

2020-11-24 04:33 UTC, merged